### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Misio12320** [ShaneBeee/Skript-Paper#1]
Hello. A suggestions. (Excelent expression with view distance I arleady suggested it to vanilla Skript. Does it works? Because on Paper vanilla does not work so a question.) 
1.on raid start:
2. If raid is from south:

**Comment by ShaneBeee** [comment]
> Hello. A suggestions. (Excelent expression with view distance I arleady suggested it to vanilla Skript. Does it works? Because on Paper vanilla does not work so a question.)

Yes the view distance expression works, I'm not sure which version it was introduced in, but it works up until 1.13.2 ... it was removed in 1.14 (in Paper) due to some issues with it. The Paper team is currently working to reimplement it.

> 1.on raid start:
> 2. If raid is from south:

There are currently no events or any API for raids yet in Spigot or Paper. Someone recently did a PR for a whole bunch of raid stuff in Spigot, so once that becomes available I will take a look at it.

**Comment by Misio12320** [comment]
Yeah the view distance on 1.14 does not work hm. I was thinking if the addon will work with view distance but its software (Paper) problem so plugins cannot do anything with this' as I good see pff. Great with the raid I'm very Interesting with this thing. Good if I get more ideas I will say. Thanks

**Comment by ShaneBeee** [comment]
> view distance I arleady suggested it to vanilla Skript. 

Also to let you know, I wrote it into Skript, the PR is still pending as Bensku is waiting for Paper to fix it in 1.14.x

https://github.com/SkriptLang/Skript/pull/2113

**Comment by Misio12320** [comment]
+ on golem rage: event hm? but not rage, another word

**Comment by ShaneBeee** [comment]
> * on golem rage: event hm? but not rage, another word

Is there a Paper event for that?

**Comment by Misio12320** [comment]
hey you. Might add "make entity pickup diamond"

**Comment by ShaneBeee** [comment]
> hey you. Might add "make entity pickup diamond"

Im not sure what you mean by this. Theres already syntaxes to give an item to player, I dont really understand what a pickup item would be for? I also don't see how this relates to Paper.
If you would like something to be added to this plugin, please make sure its only something Paper can do and provide more details on what it will do, and why you feel it should be added.
Based on your vague wording I dont see anything in Paper that would do what you are asking.



> Edit: So if software does not have this option so why you don't add a script from Minecraft vanilla? E.g. villager in vanilla can e.g fly and this does not exisist in paper so why you don't go behind the code paper and get into the fly of villager from vanilla? If I wrote correctly example.

This add-on is called Skript-Paper ... I dont understand why you are assuming this would add something that is unrelated to paper.
Same as my last response, if you want something added please do some research, maybe even send some links to methods/events/etc that relate to the PaperAPI.

Im closing this for now because I feel its just rambling on at this point.
If you would like something added please do the following:
- Create a new issue (rather than replying to one issue)
- Do some research, find out if the PaperAPI supports what you are wanting
- Give greater detail on what you would like added. Including suggested syntax, what it does, and why you think it should be added.
